/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package boite;

import form.form_achat;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import testelogin1.ConnexionBD;

public class modifAchat extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(modifAchat.class.getName());
     
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement Ps = null;
    
    
    
    public modifAchat(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        conn = ConnexionBD.conexion();
        
        initComponents();
        afficher();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idVoiture = new javax.swing.JTextField();
        numAchat = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnEffacer = new javax.swing.JButton();
        modif = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        idClient = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable Static Display", 1, 18)); // NOI18N
        jLabel1.setText("ID Client   :");

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable Static Display", 1, 18)); // NOI18N
        jLabel2.setText("ID Voiture             :");

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable Static Display", 1, 18)); // NOI18N
        jLabel3.setText("Date                        :");

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable Static Display", 1, 18)); // NOI18N
        jLabel4.setText("Nombre                :");

        idVoiture.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        idVoiture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idVoitureActionPerformed(evt);
            }
        });

        numAchat.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        numAchat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numAchatActionPerformed(evt);
            }
        });

        nombre.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable Static Display", 1, 36)); // NOI18N
        jLabel5.setText("EDIT ACHAT");

        btnEffacer.setFont(new java.awt.Font("Segoe UI Variable Static Display", 1, 18)); // NOI18N
        btnEffacer.setText("EFFACER");
        btnEffacer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEffacerMouseClicked(evt);
            }
        });
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        modif.setFont(new java.awt.Font("Segoe UI Variable Static Display", 1, 18)); // NOI18N
        modif.setText("OK");
        modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable Static Display", 1, 18)); // NOI18N
        jLabel6.setText("Numero Achat   :");

        idClient.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        idClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numAchat, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnEffacer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(modif)
                                        .addGap(25, 25, 25))
                                    .addComponent(idVoiture)
                                    .addComponent(nombre)
                                    .addComponent(idClient, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel5)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idClient, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idVoiture, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modif)
                    .addComponent(btnEffacer))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idVoitureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idVoitureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idVoitureActionPerformed

    private void numAchatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numAchatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numAchatActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEffacerActionPerformed

    private void modifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifActionPerformed

        
        java.util.Date utilDate = date.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String strDate = sdf.format(utilDate);
        
        if(numAchat.getText().isEmpty() || idClient.getText().isEmpty() || idVoiture.getText().isEmpty() || nombre.getText().isEmpty() || date.getDate() == null ) {
            
              JOptionPane.showMessageDialog(this,
                "Veuillez remplir tout les champs .",
                "Champ vide",
                JOptionPane.WARNING_MESSAGE);
                return;
        }
        
        try {
            String requete = "UPDATE ACHAT set idcli = ? ,idvoit = ?,date = ? ,qte = ? WHERE numAchat = ? ";
            Ps = conn.prepareStatement(requete);
            Ps.setString(5,numAchat.getText());
            Ps.setString(1,idClient.getText());
            Ps.setString(2,idVoiture.getText());
            Ps.setString(3,strDate);
            Ps.setString(4,nombre.getText());

            Ps.executeUpdate();

            JOptionPane.showMessageDialog(null,"Modifier avec succes");
        }catch(Exception e) {
            System.out.println("---> Exception " + e);

        }finally {
            try{  Ps.setString(4,nombre.getText());
                rs.close();
                Ps.close();

            }catch (Exception e){
                System.out.println("--> Exception" + e);
            }
        }
    }//GEN-LAST:event_modifActionPerformed

    private void idClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClientActionPerformed

    }//GEN-LAST:event_idClientActionPerformed

    private void btnEffacerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEffacerMouseClicked
       numAchat.setText("");
       idClient.setText("");
       idVoiture.setText("");
       
       nombre.setText("");
    }//GEN-LAST:event_btnEffacerMouseClicked

    public void afficher() {
        form_achat act = new form_achat();
        String id  = act.getNumAchat();
        
        try {
            String requete = "SELECT * FROM ACHAT WHERE numAchat = ?";
            Ps = conn.prepareStatement(requete);
            Ps.setString(1, id);
            rs = Ps.executeQuery();
            
            if(rs.next()) {
                String t1 = rs.getString("numAchat");
                String t2 = rs.getString("idcli");
                String t3 = rs.getString("idvoit");
               java.sql.Date sqlDate = rs.getDate("date");
                String t5 = rs.getString("qte");
                
                numAchat.setText(t1);
                idClient.setText(t2);
                idVoiture.setText(t3);
                date.setDate(sqlDate);
                nombre.setText(t5);
            }
            
        } catch (Exception e) {
            System.out.println("--> Exception " +e);
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                modifAchat dialog = new modifAchat(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEffacer;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField idClient;
    private javax.swing.JTextField idVoiture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modif;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numAchat;
    // End of variables declaration//GEN-END:variables
}
